In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [2]:
dataset=pd.read_csv('old_car_data.csv')

In [16]:
dataset.head(4)

,car_ID,symboling,CarName,fueltype,carlength,carwidth,carheight,curbweight,enginetype,fuelsystem,stroke,compressionratio,horsepower,highwaympg,price
0,0,3,2,1,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,21,27
1,1,3,3,1,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,21,27
2,2,1,1,1,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,9.0,19,26
3,3,2,4,1,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,10.0,24,30

In [4]:
car_ID_le=LabelEncoder()
dataset['car_ID']=car_ID_le.fit_transform(dataset["car_ID"])

In [5]:
car_Name_le=LabelEncoder()
dataset['CarName']=car_Name_le.fit_transform(dataset["CarName"])

In [6]:
fuel_type_le=LabelEncoder()
dataset['fueltype']=fuel_type_le.fit_transform(dataset["fueltype"])

In [7]:
input_data=dataset.iloc[:,:-1]
output_data=dataset["price"]

In [8]:
from sklearn.preprocessing import StandardScaler

In [15]:
ss = StandardScaler()
input_data = pd.DataFrame(ss.fit_transform(input_data),columns = input_data.columns)

,car_ID,symboling,CarName,fueltype,carlength,carwidth,carheight,curbweight,enginetype,fuelsystem,stroke,compressionratio,horsepower,highwaympg
0,-1.723622,1.743470,-1.838221,0.328798,-1.690772,-0.426521,-0.844782,-2.020417,-0.014566,0.074449,0.519071,-1.839377,-0.288349,-0.646553
1,-1.706724,1.743470,-1.813780,0.328798,-1.690772,-0.426521,-0.844782,-2.020417,-0.014566,0.074449,0.519071,-1.839377,-0.288349,-0.646553
2,-1.689826,0.133509,-1.862662,0.328798,-0.708596,-0.231513,-0.190566,-0.543527,0.514882,0.604046,-2.404880,0.685946,-0.288349,-0.953012
3,-1.672928,0.938490,-1.789339,0.328798,0.173698,0.207256,0.136542,0.235942,-0.420797,-0.431076,-0.517266,0.462183,-0.035973,-0.186865
4,-1.656029,0.938490,-1.764897,0.328798,0.107110,0.207256,0.230001,0.235942,0.516807,0.218885,-0.517266,0.462183,-0.540725,-1.106241
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,1.656029,-1.476452,1.510231,0.328798,1.721873,1.198549,1.398245,0.728239,0.763241,0.339248,1.666445,-0.336970,-0.162161,-0.340094
201,1.672928,-1.476452,1.485790,0.328798,1.721873,1.198549,1.351515,0.728239,0.949992,0.339248,1.666445,-0.336970,-0.364062,-0.953012
202,1.689826,-1.476452,1.534673,0.328798,1.721873,1.198549,1.398245,0.728239,0.878757,1.109571,0.926204,-1.232021,-0.338824,-1.106241
203,1.706724,-1.476452,1.583555,-3.041381,1.721873,1.198549,1.398245,0.728239,1.273437,0.435538,-1.183483,0.462183,3.244916,0.119594
204,1.723622,-1.476452,1.607996,0.328798,1.721873,1.198549,1.398245,0.728239,0.975021,0.339248,1.666445,-0.336970,-0.162161,-0.953012

In [17]:
from sklearn.model_selection import train_test_split
dataset.head(5)

,car_ID,symboling,CarName,fueltype,carlength,carwidth,carheight,curbweight,enginetype,fuelsystem,stroke,compressionratio,horsepower,highwaympg,price
0,0,3,2,1,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,21,27
1,1,3,3,1,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,21,27
2,2,1,1,1,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,9.0,19,26
3,3,2,4,1,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,10.0,24,30
4,4,2,5,1,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,8.0,18,22

In [19]:
x_train,x_test,y_train,y_test =train_test_split(input_data,output_data,train_size=0.2,random_state=42)

In [20]:
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor(n_estimators = 100)
rf.fit(x_train,y_train)
rf.score(x_train,y_train)*100, rf.score(x_test,y_test)*100

(98.09190626303834, 89.01170774459301)

In [24]:
from sklearn.metrics import mean_squared_error , mean_absolute_error
mean_squared_error(y_test,rf.predict(x_test)),mean_absolute_error(y_test,rf.predict(x_test))

(5.034497560975609, 1.414390243902439)

In [25]:
x_test

,car_ID,symboling,CarName,fueltype,carlength,carwidth,carheight,curbweight,enginetype,fuelsystem,stroke,compressionratio,horsepower,highwaympg
15,-1.470148,-0.671472,-1.569367,0.328798,0.789639,1.214799,0.463650,0.810288,1.298465,1.976184,1.074252,0.430217,-0.540725,-1.412700
9,-1.571538,-0.671472,-1.691573,0.328798,0.123757,0.337262,0.930947,-0.707626,0.957693,0.098522,-0.739338,0.462183,-0.793101,-1.412700
100,-0.033797,-0.671472,0.043756,0.328798,-0.259126,-0.052755,-0.330755,0.400041,-0.488182,-0.166277,0.000903,0.685946,-0.414537,0.272823
132,0.506948,1.743470,0.581463,0.328798,0.057168,1.019791,0.276731,0.974387,0.197213,-0.142204,0.778156,-0.592699,-0.210112,-0.646553
68,-0.574541,-1.476452,-1.471602,-3.041381,1.871697,1.369181,2.052461,2.041030,2.299604,1.350297,0.926204,1.229370,2.866352,-0.493324
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,-0.726625,0.133509,-0.591717,0.328798,0.007227,0.304760,0.276731,-0.010206,-0.328385,-0.118132,0.222975,0.430217,-0.389299,0.119594
176,1.250471,-1.476452,0.923641,0.328798,0.606521,0.126002,0.276731,0.482090,-0.272552,-0.118132,-0.073121,0.909709,-0.364062,0.272823
131,0.490049,0.938490,0.557022,0.328798,-0.442243,0.223507,0.323461,-1.322997,-0.183990,0.122594,0.482059,2.060489,-0.364062,-0.340094
17,-1.436352,-0.671472,-1.593808,0.328798,1.871697,1.864827,2.332839,1.056437,1.827913,1.976184,1.074252,0.430217,-0.540725,-1.565929
72,-0.506948,1.743470,-1.324955,0.328798,-0.359008,0.507894,2.145920,-1.199923,2.174461,2.578000,0.482059,-0.496800,-0.465012,-1.412700

In [30]:
rf.predict([[-1.470148,-0.671472,-1.569367,0.328798,0.789639,1.214799,0.463650,0.810288,1.298465,1.976184,1.074252,0.430217,-0.540725,-1.412700]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([23.32])

In [31]:
y_test

15     22
9      22
100    34
132    28
68     25
       ..
59     32
176    32
131    31
17     20
72     18
Name: price, Length: 164, dtype: int64